{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "livesync-manager.serviceAccountName" . }}
  labels:
    {{- include "livesync-manager.labels" . | nindent 4 }}
automountServiceAccountToken: {{ and .Values.telemetry.couchdbLogs.enabled .Values.telemetry.couchdbLogs.createRbac }}
{{- end }}
